fig1:
	dot -Tpng fig1.dot > fig1.png
	mv fig1.png ../images

diagram1:
	dot -Tpng diagram1.dot > diagram1.png
	mv diagram1.png ../images

diagram2:
	dot -Tpng diagram2.dot > diagram2.png
	mv diagram2.png ../images

diagram3:
	dot -Tpng diagram3.dot > diagram3.png
	mv diagram3.png ../images

diagram4:
	dot -Tpng diagram4.dot > diagram4.png
	mv diagram4.png ../images
